
CREATE SEQUENCE seq_ejemplo
START WITH 1
INCREMENT BY 2
NOCACHE
NOCYCLE;


CREATE TABLE ejemplo(
    idejemplo INT NOT NULL PRIMARY KEY,
    texto VARCHAR2(30)
);

INSERT INTO ejemplo(
    idejemplo,
    texto
)
VALUES
(seq_ejemplo.nextval, 'CCCCC');


/*
secuencia descendente
*/

CREATE SEQUENCE seq_descendente
    START WITH 100
    INCREMENT BY -10
    MINVALUE 0
    MAXVALUE 100
    NOCYCLE;

/*Para > ORACLE 12c*/
/*que sea generada por defecto en cada inser*/

CREATE TABLE productos (
    producto_id  NUMBER DEFAULT seq_productos.NEXTVAL PRIMARY KEY,
    nombre       VARCHAR2(200),
    precio       NUMBER
);

INSERT INTO productos (nombre, precio) VALUES ('Laptop', 1500);
INSERT INTO productos (nombre, precio) VALUES ('Mouse', 25);
INSERT INTO productos (nombre, precio) VALUES ('Teclado', 80);

/*secuencias con identity ORACLE > 12c*/
/*secuencia por defecto*/
CREATE TABLE clientes (
    cliente_id  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100),
    email       VARCHAR2(200)
);

/*secuencia por defecto moficada*/
CREATE TABLE proveedores (
    proveedor_id  NUMBER GENERATED BY DEFAULT AS IDENTITY
                  START WITH 500 INCREMENT BY 10
                  PRIMARY KEY,
    nombre        VARCHAR2(100)
);


/*listar las secuencias*/
SELECT sequence_name,
       min_value,
       max_value,
       increment_by,
       cycle_flag,
       cache_size,
       last_number       -- Último valor cacheado/generado
FROM user_sequences;